name: CI/CD vite02

on:
  push:
    branches: [prod]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker_compose Build
        run: docker-compose -f docker-compose.prod.yml build

      - name: docker_compose Up
        run: docker-compose run -f docker-compose.prod.yml -e HOST=${{ secrets.HOST  }}

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          ssh ${{ secrets.AWS_PRIVATE_KEY  }} ${USER_NAME}@${HOSTNAME}

            #Now we have got the access of EC2 and we will start the deploy
            cd /home/ubuntu/vite02 &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            docker-compose run -f docker-compose.prod.yml -e HOST=${{ secrets.HOST  }}
