name: CI/CD vite02
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: docker_compose Build
        run: docker-compose -f docker-compose.prod.yml build --build-arg HOST=${{ secrets.HOST }}
      - name: docker_compose Up
        run: docker-compose run -f docker-compose.prod.yml -e HOST=${{ secrets.HOST }}
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          AWS_DEFAULT_REGION: eu-west-3
        run: |
          echo "${PRIVATE_KEY}" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-15-236-172-168.eu-west-3.compute.amazonaws.com '

            cd vite02 &&
            git checkout prod &&
            git fetch --all &&
            git reset --hard origin/prod &&
            cd server &&
            echo "HOST=${{ secrets.HOST }} 
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} 
            REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" > .env && 
            sudo chmod 400 .env && 
            cd .. &&
            sudo docker-compose -f docker-compose.prod.yml build &&
            sudo docker-compose -f docker-compose.prod.yml up -d
          '
